# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  pr_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'NPM Install and Build'
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - run: npm install
    - run: npm run build
